//! Embed the `kata` workflow plugin (the repo's `.claude/plugins/kata/`) into
//! the engine at build time, so `catalog::discover` can offer it as a
//! `builtin` source in any workdir. Generates `$OUT_DIR/builtin_kit.rs` with a
//! `FILES: &[(&str, &[u8])]` table of (relative path, contents) pairs; an
//! absent plugin dir (e.g. a published crate built outside this repo) yields
//! an empty table and the builtin source simply never appears.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let kit = manifest.join("..").join("..").join(".claude/plugins/kata");
    // A dir-level rerun only catches direct child add/remove; per-file lines
    // below catch content edits.
    println!("cargo:rerun-if-changed={}", kit.display());

    let mut files = Vec::new();
    if kit.is_dir() {
        collect(&kit, &kit, &mut files);
    }
    files.sort();

    let mut src = String::from(
        "/// (relative path, contents) of every file in the builtin `kata` plugin.\n\
         /// Generated by build.rs from `.claude/plugins/kata/`; empty when the\n\
         /// crate is built outside a kata working tree.\n\
         pub static FILES: &[(&str, &[u8])] = &[\n",
    );
    for rel in &files {
        let abs = kit.join(rel).canonicalize().unwrap();
        println!("cargo:rerun-if-changed={}", abs.display());
        src.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            abs.display().to_string()
        ));
    }
    src.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("builtin_kit.rs");
    std::fs::write(out, src).unwrap();
}

/// Walk `dir` collecting file paths relative to `root`, with `/` separators so
/// the embedded table is platform-stable. Symlinks are skipped, never followed
/// (same rule as `fsutil::copy_dir`: vendoring must not escape the tree).
fn collect(root: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in std::fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let ft = entry.file_type().unwrap();
        if ft.is_symlink() {
            continue;
        }
        let path = entry.path();
        if ft.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path.strip_prefix(root).unwrap();
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}
