// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Auth = { 
/**
 * Run in the empty room (`--bare`). Default true.
 */
bare: boolean, 
/**
 * Env var holding the API token; forwarded to `ANTHROPIC_API_KEY` under bare mode.
 */
token_env?: string | null, };
