// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

export type CatalogEntry = { kind: EntryKind, name: string, description: string, source: string, path: string, provides: Array<string>, mcp_servers: Array<string>, };
