// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityMode } from "./IdentityMode";

export type Identity = { system_prompt?: string | null, mode: IdentityMode, };
