// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityMode } from "./IdentityMode";

export type Identity = { 
/**
 * A system prompt to append to, or replace, the default.
 */
system_prompt?: string | null, 
/**
 * How `system_prompt` combines with the default: append or replace.
 */
mode: IdentityMode, };
