// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Interactive = { 
/**
 * Opt-in gate. When false, the engine never wires the ask_user tool, so
 * claude has no way to pause on the operator. Claude's built-in
 * AskUserQuestion is disallowed on every run regardless (it terminates a
 * headless session), so a non-interactive run must decide for itself.
 */
enabled: boolean, 
/**
 * How long the engine waits on the operator's answer before reaping the run
 * (exit 123). Unset = wait indefinitely until answered or cancelled.
 */
answer_timeout_secs?: number | null, };
