// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Interactive = { 
/**
 * Opt-in gate. When false, the engine never wires the ask_user tool, so
 * claude cannot pause — behaviour is identical to a non-interactive run.
 */
enabled: boolean, 
/**
 * How long the engine waits on the operator's answer before reaping the run
 * (exit 123). Unset = wait indefinitely until answered or cancelled.
 */
answer_timeout_secs?: number | null, };
