// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KataLoadFailure } from "./KataLoadFailure";
import type { RunSpec } from "./RunSpec";

/**
 * The library listing: the katas that loaded, and the files that did not.
 *
 * Both halves are reported on purpose. Dropping the failures would make a
 * broken kata simply vanish from the library — no entry, no error, no way to
 * tell it had ever been saved. A file the operator wrote and can no longer see
 * is worse than one they can see is broken.
 */
export type KataListing = { 
/**
 * Loaded katas, sorted by name.
 */
katas: Array<RunSpec>, 
/**
 * Files that failed to load, sorted by path. Empty in the healthy case.
 */
failures: Array<KataLoadFailure>, };
