// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `*.toml` in the library that could not be loaded.
 */
export type KataLoadFailure = { 
/**
 * Full path, so the operator can go and fix the file.
 */
path: string, 
/**
 * Why it failed, verbatim from the loader.
 */
message: string, };
