// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Isolation } from "./Isolation";

export type Leash = { 
/**
 * Turn cap (exit 125). Unset = unbounded, limited only by the timeout.
 */
max_turns?: number | null, 
/**
 * Wall-clock cap in seconds (exit 124). Unset applies the 1800s default.
 */
timeout_secs?: number | null, 
/**
 * Spend ceiling in USD (exit 122). Must be > 0 when set.
 */
max_budget_usd?: number | null, 
/**
 * Isolation mode: run in place, or branch off HEAD into a worktree.
 */
isolation: Isolation, };
