// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Isolation } from "./Isolation";

export type Leash = { max_turns?: number | null, timeout_secs?: number | null, max_budget_usd?: number | null, isolation: Isolation, };
