// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = { 
/**
 * Model id (e.g. `opus`). Unset uses claude's default.
 */
id?: string | null, };
