// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";
import type { UnmatchedPolicy } from "./UnmatchedPolicy";

export type Permissions = { 
/**
 * How claude's permission checks are answered: `bypass` (the default,
 * `--dangerously-skip-permissions`), `prompt` (Kata's MCP tool decides every
 * call), or `auto` (claude's own classifier decides, with Kata's MCP tool
 * consulted only for a call an `ask` rule forces to the operator).
 */
mode: PermissionMode, 
/**
 * Rules auto-allowed under `mode = "prompt"`. Claude rule syntax: `Tool` or
 * `Tool(specifier)`, with `*` as a wildcard — e.g. `Bash(git *)`.
 */
allow?: Array<string>, 
/**
 * Rules auto-denied under `mode = "prompt"`. Evaluated before `allow`, so a
 * deny cannot be re-opened by a broader allow.
 */
deny?: Array<string>, 
/**
 * Rules that force the operator prompt under `mode = "prompt"` or `"auto"`.
 * Same claude syntax as `allow`/`deny` (`Tool` or `Tool(specifier)`, `*`
 * wildcard). A matching call is routed to Kata's `approve_tool` and pauses
 * on the operator, so a non-empty list requires `[interactive] enabled = true`.
 */
ask?: Array<string>, 
/**
 * What happens to a call no rule matched: ask the operator (the default,
 * which requires `[interactive] enabled = true`), deny it, or allow it.
 */
unmatched: UnmatchedPolicy, };
