// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginConfig = { 
/**
 * Whether the plugin exposes an MCP server to wire in. Unset = inherit the plugin's own default.
 */
mcp?: boolean | null, 
/**
 * Environment variable names to forward to the plugin, resolved from the parent environment.
 */
env?: Array<string>, };
