// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunRecord = { id: string, kata: string, started_at: number, isolation: string, exit?: number | null, turns?: number | null, cost_usd?: number | null, duration_ms?: number | null, result?: string | null, };
