// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Auth } from "./Auth";
import type { Identity } from "./Identity";
import type { Interactive } from "./Interactive";
import type { Leash } from "./Leash";
import type { Model } from "./Model";
import type { PluginConfig } from "./PluginConfig";

export type RunSpec = { schema: number, name: string, description?: string | null, task: string, context?: string | null, workdir: string, identity: Identity, skills: Array<string>, plugins: { [key in string]?: PluginConfig }, model: Model, leash: Leash, auth: Auth, interactive: Interactive, };
